add mute button in channel header
uber-uchat/mattermost-webapp pull request #81
Opened 2019-10-15 11:39 UTC by satyanan

#### Summary
Adds a mute button to channel header. Clicking this will mute the channel

#### Ticket Link

#### Related Pull Requests

2019-10-15 12:10 UTC, amitmall requested changes

2019-10-15 12:10 UTC, amitmall commented on components/channel_header_mobile/channel_header_mobile.js
> +                                        <MuteChannelButton
reuse UnmuteChannelButton.

2019-10-16 06:23 UTC, satyanan commented on components/channel_header_mobile/channel_header_mobile.js
> +                                        <MuteChannelButton
Done. Reusing UnmuteChannelButton with additional props `muted`

2019-10-16 06:43 UTC, bhaskaruniz commented on components/channel_header_mobile/unmute_channel_button/unmute_channel_button.js
> +        updateChannelNotifyProps(user.id, channel.id, {mark_unread: muted ? NotificationLevels.ALL : NotificationLevels.MENTION});
where do we set the value to the 'muted' boolean?  will it be set after executing updateChannelNotifyProps method, if its not the condition should be reversed I think "{mark_unread: muted ? NotificationLevels.MENTION : NotificationLevels.ALL})"

2019-10-16 08:57 UTC, satyanan commented on components/channel_header_mobile/unmute_channel_button/unmute_channel_button.js
> +        updateChannelNotifyProps(user.id, channel.id, {mark_unread: muted ? NotificationLevels.ALL : NotificationLevels.MENTION});
`muted` holds current status of channel(whether muted or not) and comes indirectly through redux. So, yes `updateChannelNotifyProps` updates it. 

The condition seems correct, since if currently muted(muted===true) then unmute(change to NotificationLevels.ALL then as a side-effect of `updateChannelNotifyProps` call `muted` should become false.

2019-11-21 09:57 UTC, amitmall approved these changes

2019-11-21 10:22 UTC, merged